In [2]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

file_path = "/content/final_regression_dataset_v2.xlsx"   # adapte si besoin
df = pd.read_excel(file_path, sheet_name="regression_base")

base_2022 = df[df["fiscal_year"] == 2022].copy()

print(base_2022.shape)
base_2022[["firm_id", "book_leverage", "interest_coverage"]].head()

(196, 30)

   firm_id  book_leverage  interest_coverage
0     F001       0.317002          40.749574
4     F002       0.152152          20.439599
8     F003       0.247720          42.546610
12    F004       0.145134           5.174482
16    F005       0.040248         209.641457

In [3]:
lev_cut = base_2022["book_leverage"].quantile(0.67)
ic_cut = base_2022["interest_coverage"].quantile(0.33)

print("Leverage cutoff (67th percentile):", lev_cut)
print("Interest coverage cutoff (33rd percentile):", ic_cut)

Leverage cutoff (67th percentile): 0.3167675675576231
Interest coverage cutoff (33rd percentile): 9.57081452164009

In [4]:
base_2022["vulnerable_2022"] = (
    (base_2022["book_leverage"] >= lev_cut) &
    (base_2022["interest_coverage"] <= ic_cut)
).astype(int)

print(base_2022["vulnerable_2022"].value_counts())

vulnerable_2022
0    162
1     34
Name: count, dtype: int64

In [5]:
vuln_map = base_2022[["firm_id", "vulnerable_2022"]].copy()

df = df.merge(vuln_map, on="firm_id", how="left")

print(df["vulnerable_2022"].value_counts(dropna=False))

vulnerable_2022
0.0    639
1.0    136
NaN      6
Name: count, dtype: int64

In [6]:
df["rate_change_x_vulnerable_2022"] = df["policy_rate_change"] * df["vulnerable_2022"]

df[[
    "firm_id",
    "fiscal_year",
    "policy_rate_change",
    "vulnerable_2022",
    "rate_change_x_vulnerable_2022"
]].head()

,firm_id,fiscal_year,policy_rate_change,vulnerable_2022,rate_change_x_vulnerable_2022
0,F001,2022,NaN,0.0,NaN
1,F001,2023,1.23,0.0,0.0
2,F001,2024,-0.85,0.0,-0.0
3,F001,2025,-0.76,0.0,-0.0
4,F002,2022,NaN,0.0,NaN

In [7]:
reg_cols = [
    "firm_id",
    "fiscal_year",
    "roa_ebit",
    "policy_rate_change",
    "vulnerable_2022",
    "rate_change_x_vulnerable_2022",
    "size_ln_assets"
]

reg_vuln = df[reg_cols].dropna().copy()

print("Observations:", len(reg_vuln))
print("Firmes:", reg_vuln["firm_id"].nunique())
print("Années:", sorted(reg_vuln["fiscal_year"].unique()))

Observations: 576
Firmes: 195
Années: [np.int64(2023), np.int64(2024), np.int64(2025)]

In [8]:
model_vuln_roaebit = smf.ols(
    "roa_ebit ~ policy_rate_change + rate_change_x_vulnerable_2022 + size_ln_assets + C(firm_id) + C(fiscal_year)",
    data=reg_vuln
).fit(cov_type="cluster", cov_kwds={"groups": reg_vuln["firm_id"]})

print(model_vuln_roaebit.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               roa_ebit   R-squared:                       0.874
Model:                            OLS   Adj. R-squared:                  0.807
Method:                 Least Squares   F-statistic:                     9796.
Date:                Sun, 05 Apr 2026   Prob (F-statistic):          4.82e-231
Time:                        23:00:02   Log-Likelihood:                 1306.4
No. Observations:                 576   AIC:                            -2213.
Df Residuals:                     376   BIC:                            -1342.
Df Model:                         199
Covariance Type:              cluster
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                        -0.0790      1.329     -0.059      0.953      -2.684       2.526
C(firm_id)[T.F002]               -0.0915      0.012     -7.703      0.000      -0.115      -0.068
C(firm_id)[T.F003]               -0.0482      0.084     -0.573      0.567      -0.213       0.117
C(firm_id)[T.F004]               -0.2401      0.029     -8.224      0.000      -0.297      -0.183
C(firm_id)[T.F005]               -0.1026      0.014     -7.393      0.000      -0.130      -0.075
C(firm_id)[T.F006]               -0.0927      0.012     -7.869      0.000      -0.116      -0.070
C(firm_id)[T.F007]               -0.1545      0.053     -2.938      0.003      -0.258      -0.051
C(firm_id)[T.F008]               -0.1979      0.048     -4.145      0.000      -0.292      -0.104
C(firm_id)[T.F010]               -0.0413      0.124     -0.332      0.740      -0.285       0.203
C(firm_id)[T.F011]               -0.1932      0.057     -3.410      0.001      -0.304      -0.082
C(firm_id)[T.F012]               -0.2382      0.047     -5.084      0.000      -0.330      -0.146
C(firm_id)[T.F013]               -0.2204      0.143     -1.546      0.122      -0.500       0.059
C(firm_id)[T.F014]               -0.1811      0.124     -1.464      0.143      -0.423       0.061
C(firm_id)[T.F015]               -0.2720      0.081     -3.347      0.001      -0.431      -0.113
C(firm_id)[T.F016]               -0.1031      0.118     -0.873      0.383      -0.335       0.128
C(firm_id)[T.F017]               -0.1085      0.095     -1.137      0.255      -0.295       0.078
C(firm_id)[T.F018]               -0.0480      0.120     -0.401      0.688      -0.282       0.186
C(firm_id)[T.F019]               -0.2644      0.084     -3.153      0.002      -0.429      -0.100
C(firm_id)[T.F020]                0.0037      0.159      0.023      0.981      -0.309       0.316
C(firm_id)[T.F021]                0.0136      0.148      0.092      0.927      -0.277       0.304
C(firm_id)[T.F022]               -0.2372      0.150     -1.579      0.114      -0.532       0.057
C(firm_id)[T.F023]               -0.0629      0.163     -0.386      0.699      -0.382       0.256
C(firm_id)[T.F024]               -0.3372      0.030    -11.378      0.000      -0.395      -0.279
C(firm_id)[T.F025]               -0.3226      0.043     -7.546      0.000      -0.406      -0.239
C(firm_id)[T.F026]               -0.2156      0.068     -3.184      0.001      -0.348      -0.083
C(firm_id)[T.F027]               -0.0875      0.074     -1.186      0.236      -0.232       0.057
C(firm_id)[T.F028]               -0.1934      0.034     -5.635      0.000      -0.261      -0.126
C(firm_id)[T.F029]               -0.2164      0.049     -4.393      0.000      -0.313      -0.120
C(firm_id)[T.F030]               -0.1825      0.055     -3.299      0.001      -0.291      -0.074
C(firm_id)[T.F031]               -0.2774      0.026    -10.785      0.000      -0.328      -0.227
C(firm_id)[T.F032]               -0.2329      0.063     -3.679      0.000      -0.357      -0.109
C(firm_id)[T.F033]               -0.2125      0.075     -2.823      0.005      -0.360      -0.065
C(firm_id)[T.F034]               -0.2411      0.074     -3.242      0.001      -0.387      -0.095
C(firm_id)[T.F035]               -0.1505      0.150     -1.004      0.315      -0.444       0.143
C(firm_id)[T.F036]               -0.2184      0.111     -1.965      0.049      -0.436      -0.001
C(firm_id)[T.F037]               -0.1965      0.106     -1.853      0.064      -0.404       0.011
C(firm_id)[T.F038]               -0.0925      0.117     -0.791      0.429      -0.322       0.137
C(firm_id)[T.F039]               -0.0453      0.160     -0.282      0.778      -0.360       0.269
C(firm_id)[T.F040]               -0.2247      0.010    -21.717      0.000      -0.245      -0.204
C(firm_id)[T.F041]               -0.2471      0.068     -3.627      0.000      -0.381      -0.114
C(firm_id)[T.F042]               -0.1838      0.114     -1.611      0.107      -0.407       0.040
C(firm_id)[T.F043]               -0.2826      0.018    -15.747      0.000      -0.318      -0.247
C(firm_id)[T.F044]               -0.1127      0.091     -1.242      0.214      -0.291       0.065
C(firm_id)[T.F045]               -0.2528      0.042     -5.996      0.000      -0.335      -0.170
C(firm_id)[T.F046]               -0.1023      0.096     -1.061      0.289      -0.291       0.087
C(firm_id)[T.F047]               -0.2641      0.030     -8.917      0.000      -0.322      -0.206
C(firm_id)[T.F048]               -0.2347      0.015    -15.849      0.000      -0.264      -0.206
C(firm_id)[T.F049]               -0.2353      0.027     -8.842      0.000      -0.288      -0.183
C(firm_id)[T.F050]               -0.2551      0.004    -63.780      0.000      -0.263      -0.247
C(firm_id)[T.F051]               -0.2359      0.099     -2.375      0.018      -0.431      -0.041
C(firm_id)[T.F052]               -0.0131      0.130     -0.101      0.919      -0.268       0.241
C(firm_id)[T.F053]               -0.1775      0.142     -1.252      0.211      -0.456       0.100
C(firm_id)[T.F054]               -0.1944      0.166     -1.169      0.242      -0.520       0.132
C(firm_id)[T.F055]               -0.1304      0.123     -1.058      0.290      -0.372       0.111
C(firm_id)[T.F056]               -0.1495      0.113     -1.325      0.185      -0.371       0.072
C(firm_id)[T.F057]               -0.0604      0.103     -0.587      0.557      -0.262       0.141
C(firm_id)[T.F058]               -0.0363      0.072     -0.501      0.616      -0.178       0.106
C(firm_id)[T.F059]               -0.0889      0.126     -0.707      0.480      -0.335       0.158
C(firm_id)[T.F060]               -0.0364      0.185     -0.197      0.844      -0.399       0.326
C(firm_id)[T.F062]               -0.2084      0.093     -2.233      0.026      -0.391      -0.026
C(firm_id)[T.F063]               -0.1510      0.054     -2.777      0.005      -0.258      -0.044
C(firm_id)[T.F064]               -0.1859      0.065     -2.881      0.004      -0.312      -0.059
C(firm_id)[T.F065]               -0.1812      0.064     -2.814      0.005      -0.307      -0.055
C(firm_id)[T.F066]               -0.0861      0.085     -1.008      0.314      -0.254       0.081
C(firm_id)[T.F067]               -0.2368      0.095     -2.481      0.013      -0.424      -0.050
C(firm_id)[T.F068]               -0.0396      0.155     -0.255      0.799      -0.344       0.265
C(firm_id)[T.F069]               -0.1659      0.069     -2.405      0.016      -0.301      -0.031
C(firm_id)[T.F070]               -0.2056      0.061     -3.364      0.001      -0.325      -0.086
C(firm_id)[T.F071]               -0.1871      0.082     -2.275      0.023      -0.348      -0.026
C(firm_id)[T.F072]               -0.2099      0.093     -2.248      0.025      -0.393      -0.027
C(firm_id)[T.F073]               -0.2730      0.039     -6.979      0.000      -0.350      -0.196
C(firm_id)[T.F074]               -0.1563      0.093     -1.673      0.094      -0.339       0.027
C(firm_id)[T.F075]               -0.3226      0.043     -7.546      0.000      -0.406      -0.239
C(firm_id)[T.F076]               -0.1800      0.081     -2.217      0.027      -0.339      -0.021
C(firm_id)[T.F077]               -0.2294      0.071     -3.232      0.001      -0.369      -0.090
C(firm_id)[T.F078]               -0.1577      0.083     -1.893      0.058      -0.321       0.006
C(firm_id)[T.F079]               -0.1719      0.107     -1.613      0.107      -0.381       0.037
C(firm_id)[T.F080]               -0.1725      0.111     -1.550      0.121      -0.391       0.046
C(firm_id)[T.F081]               -0.1522      0.125     -1.214      0.225      -0.398       0.094
C(firm_id)[T.F082]               -0.1130      0.144     -0.783      0.434      -0.396       0.170
C(firm_id)[T.F083]               -0.1053      0.160     -0.657      0.511      -0.420       0.209
C(firm_id)[T.F084]               -0.1722      0.138     -1.249      0.212      -0.442       0.098
C(firm_id)[T.F085]               -0.2233      0.152     -1.472      0.141      -0.521       0.074
C(firm_id)[T.F086]               -0.1923      0.074     -2.592      0.010      -0.338      -0.047
C(firm_id)[T.F087]               -0.2329      0.114     -2.039      0.041      -0.457      -0.009
C(firm_id)[T.F088]               -0.1767      0.094     -1.877      0.060      -0.361       0.008
C(firm_id)[T.F089]               -0.2109      0.008    -25.814      0.000      -0.227      -0.195
C(firm_id)[T.F090]               -0.2235      0.013    -17.422      0.000      -0.249      -0.198
C(firm_id)[T.F091]               -0.3400      0.274     -1.242      0.214      -0.876       0.196
C(firm_id)[T.F092]               -0.3505      0.227     -1.547      0.122      -0.795       0.094
C(firm_id)[T.F093]               -0.2024      0.115     -1.766      0.077      -0.427       0.022
C(firm_id)[T.F094]               -0.1807      0.105     -1.720      0.085      -0.387       0.025
C(firm_id)[T.F095]               -0.2020      0.133     -1.519      0.129      -0.463       0.059
C(firm_id)[T.F096]               -0.3038      0.178     -1.708      0.088      -0.653       0.045
C(firm_id)[T.F097]               -0.1125      0.096     -1.174      0.240      -0.300       0.075
C(firm_id)[T.F098]               -0.3210      0.218     -1.472      0.141      -0.748       0.106
C(firm_id)[T.F099]               -0.1969      0.104     -1.892      0.058      -0.401       0.007
C(firm_id)[T.F100]               -0.2018      0.108     -1.871      0.061      -0.413       0.010
C(firm_id)[T.F101]               -0.1099      0.089     -1.239      0.215      -0.284       0.064
C(firm_id)[T.F102]               -0.2664      0.079     -3.380      0.001      -0.421      -0.112
C(firm_id)[T.F103]               -0.2623      0.083     -3.151      0.002      -0.425      -0.099
C(firm_id)[T.F104]               -0.2787      0.108     -2.591      0.010      -0.490      -0.068
C(firm_id)[T.F105]               -0.1333      0.058     -2.305      0.021      -0.247      -0.020
C(firm_id)[T.F106]               -0.3075      0.156     -1.971      0.049      -0.613      -0.002
C(firm_id)[T.F107]               -0.3427      0.218     -1.571      0.116      -0.770       0.085
C(firm_id)[T.F108]               -0.2749      0.129     -2.133      0.033      -0.528      -0.022
C(firm_id)[T.F109]               -0.3021      0.184     -1.646      0.100      -0.662       0.058
C(firm_id)[T.F110]               -0.2935      0.184     -1.597      0.110      -0.654       0.067
C(firm_id)[T.F111]               -0.2325      0.003    -67.286      0.000      -0.239      -0.226
C(firm_id)[T.F112]               -0.2022      0.062     -3.285      0.001      -0.323      -0.082
C(firm_id)[T.F113]               -0.1712      0.079     -2.168      0.030      -0.326      -0.016
C(firm_id)[T.F114]               -0.0908      0.158     -0.573      0.566      -0.401       0.220
C(firm_id)[T.F115]               -0.2575      0.013    -19.806      0.000      -0.283      -0.232
C(firm_id)[T.F116]               -0.1915      0.091     -2.116      0.034      -0.369      -0.014
C(firm_id)[T.F117]               -0.1646      0.103     -1.596      0.111      -0.367       0.038
C(firm_id)[T.F118]               -0.2739      0.057     -4.774      0.000      -0.386      -0.161
C(firm_id)[T.F119]               -0.1807      0.131     -1.384      0.166      -0.437       0.075
C(firm_id)[T.F120]               -0.1558      0.059     -2.622      0.009      -0.272      -0.039
C(firm_id)[T.F121]               -0.2728      0.051     -5.366      0.000      -0.372      -0.173
C(firm_id)[T.F122]               -0.2659      0.088     -3.011      0.003      -0.439      -0.093
C(firm_id)[T.F123]               -0.2647      0.047     -5.615      0.000      -0.357      -0.172
C(firm_id)[T.F124]               -0.2378      0.131     -1.816      0.069      -0.494       0.019
C(firm_id)[T.F125]               -0.1761      0.136     -1.296      0.195      -0.442       0.090
C(firm_id)[T.F126]               -0.1701      0.117     -1.454      0.146      -0.399       0.059
C(firm_id)[T.F127]               -0.1707      0.093     -1.839      0.066      -0.353       0.011
C(firm_id)[T.F128]               -0.2665      0.072     -3.686      0.000      -0.408      -0.125
C(firm_id)[T.F129]               -0.2236      0.078     -2.881      0.004      -0.376      -0.072
C(firm_id)[T.F130]               -0.1603      0.149     -1.078      0.281      -0.452       0.131
C(firm_id)[T.F131]               -0.1702      0.073     -2.348      0.019      -0.312      -0.028
C(firm_id)[T.F132]               -0.1956      0.069     -2.817      0.005      -0.332      -0.060
C(firm_id)[T.F133]               -0.2002      0.165     -1.216      0.224      -0.523       0.122
C(firm_id)[T.F134]               -0.2042      0.166     -1.233      0.218      -0.529       0.120
C(firm_id)[T.F135]               -0.1769      0.100     -1.763      0.078      -0.373       0.020
C(firm_id)[T.F136]               -0.1617      0.123     -1.319      0.187      -0.402       0.079
C(firm_id)[T.F138]               -0.2395      0.176     -1.359      0.174      -0.585       0.106
C(firm_id)[T.F140]               -0.2489      0.091     -2.746      0.006      -0.427      -0.071
C(firm_id)[T.F141]               -0.1719      0.046     -3.742      0.000      -0.262      -0.082
C(firm_id)[T.F142]               -0.0062      0.139     -0.045      0.964      -0.279       0.266
C(firm_id)[T.F143]               -0.1422      0.093     -1.528      0.126      -0.325       0.040
C(firm_id)[T.F144]               -0.2580      0.052     -4.928      0.000      -0.361      -0.155
C(firm_id)[T.F145]               -0.1998      0.011    -17.589      0.000      -0.222      -0.178
C(firm_id)[T.F146]               -0.2529      0.052     -4.873      0.000      -0.355      -0.151
C(firm_id)[T.F147]               -0.1947      0.088     -2.208      0.027      -0.367      -0.022
C(firm_id)[T.F148]               -0.2028      0.099     -2.057      0.040      -0.396      -0.010
C(firm_id)[T.F149]               -0.1896      0.131     -1.445      0.148      -0.447       0.068
C(firm_id)[T.F150]               -0.2380      0.053     -4.525      0.000      -0.341      -0.135
C(firm_id)[T.F151]               -0.2452      0.111     -2.203      0.028      -0.463      -0.027
C(firm_id)[T.F152]               -0.2123      0.113     -1.879      0.060      -0.434       0.009
C(firm_id)[T.F153]               -0.2565      0.093     -2.748      0.006      -0.439      -0.074
C(firm_id)[T.F154]               -0.2410      0.088     -2.740      0.006      -0.413      -0.069
C(firm_id)[T.F155]               -0.3132      0.054     -5.816      0.000      -0.419      -0.208
C(firm_id)[T.F156]               -0.1945      0.082     -2.380      0.017      -0.355      -0.034
C(firm_id)[T.F157]               -0.2270      0.043     -5.244      0.000      -0.312      -0.142
C(firm_id)[T.F158]               -0.2667      0.016    -16.269      0.000      -0.299      -0.235
C(firm_id)[T.F159]               -0.2646      0.016    -16.087      0.000      -0.297      -0.232
C(firm_id)[T.F160]               -0.2995      0.027    -10.949      0.000      -0.353      -0.246
C(firm_id)[T.F161]               -0.2626      0.077     -3.412      0.001      -0.413      -0.112
C(firm_id)[T.F162]               -0.3075      0.060     -5.152      0.000      -0.424      -0.191
C(firm_id)[T.F163]               -0.1928      0.126     -1.528      0.127      -0.440       0.055
C(firm_id)[T.F164]               -0.2365      0.011    -22.492      0.000      -0.257      -0.216
C(firm_id)[T.F165]               -0.2032      0.083     -2.459      0.014      -0.365      -0.041
C(firm_id)[T.F166]               -0.2203      0.146     -1.507      0.132      -0.507       0.066
C(firm_id)[T.F167]               -0.1712      0.167     -1.022      0.307      -0.499       0.157
C(firm_id)[T.F168]               -0.1843      0.163     -1.134      0.257      -0.503       0.134
C(firm_id)[T.F169]               -0.2322      0.102     -2.275      0.023      -0.432      -0.032
C(firm_id)[T.F170]               -0.2134      0.098     -2.171      0.030      -0.406      -0.021
C(firm_id)[T.F171]               -0.2004      0.051     -3.910      0.000      -0.301      -0.100
C(firm_id)[T.F172]               -0.1434      0.066     -2.174      0.030      -0.273      -0.014
C(firm_id)[T.F173]               -0.1702      0.063     -2.718      0.007      -0.293      -0.047
C(firm_id)[T.F174]               -0.1608      0.108     -1.486      0.137      -0.373       0.051
C(firm_id)[T.F175]               -0.2237      0.149     -1.498      0.134      -0.516       0.069
C(firm_id)[T.F176]               -0.1718      0.158     -1.084      0.278      -0.482       0.139
C(firm_id)[T.F177]               -0.1581      0.172     -0.918      0.359      -0.496       0.179
C(firm_id)[T.F178]               -0.2329      0.104     -2.243      0.025      -0.436      -0.029
C(firm_id)[T.F179]               -0.2434      0.124     -1.960      0.050      -0.487    2.69e-05
C(firm_id)[T.F180]               -0.1385      0.208     -0.667      0.505      -0.546       0.269
C(firm_id)[T.F181]               -0.0758      0.103     -0.734      0.463      -0.278       0.127
C(firm_id)[T.F182]               -0.1431      0.085     -1.682      0.093      -0.310       0.024
C(firm_id)[T.F183]               -0.1623      0.175     -0.928      0.354      -0.505       0.181
C(firm_id)[T.F184]               -0.2282      0.100     -2.286      0.022      -0.424      -0.033
C(firm_id)[T.F185]               -0.0753      0.216     -0.349      0.727      -0.498       0.348
C(firm_id)[T.F186]               -0.2357      0.095     -2.477      0.013      -0.422      -0.049
C(firm_id)[T.F187]               -0.1041      0.183     -0.569      0.570      -0.463       0.255
C(firm_id)[T.F188]               -0.2636      0.128     -2.067      0.039      -0.514      -0.014
C(firm_id)[T.F189]               -0.1637      0.219     -0.746      0.456      -0.594       0.266
C(firm_id)[T.F190]               -0.1132      0.158     -0.715      0.475      -0.424       0.197
C(firm_id)[T.F191]               -0.1054      0.063     -1.685      0.092      -0.228       0.017
C(firm_id)[T.F192]               -0.1925      0.113     -1.701      0.089      -0.414       0.029
C(firm_id)[T.F193]               -0.2361      0.119     -1.986      0.047      -0.469      -0.003
C(firm_id)[T.F194]               -0.1422      0.130     -1.097      0.273      -0.396       0.112
C(firm_id)[T.F195]               -0.2286      0.089     -2.557      0.011      -0.404      -0.053
C(firm_id)[T.F196]               -0.1960      0.146     -1.339      0.181      -0.483       0.091
C(firm_id)[T.F197]               -0.2164      0.105     -2.070      0.038      -0.421      -0.011

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 199, but rank is 5
  warnings.warn('covariance of constraints does not have full '

In [9]:
main_vars = [
    "policy_rate_change",
    "rate_change_x_vulnerable_2022",
    "size_ln_assets"
]

results_vuln_roaebit = pd.DataFrame({
    "coef": model_vuln_roaebit.params[main_vars],
    "std_err": model_vuln_roaebit.bse[main_vars],
    "t_stat": model_vuln_roaebit.tvalues[main_vars],
    "p_value": model_vuln_roaebit.pvalues[main_vars]
})

print(results_vuln_roaebit)

print("\nN observations :", int(model_vuln_roaebit.nobs))
print("R² :", round(model_vuln_roaebit.rsquared, 4))
print("Adj. R² :", round(model_vuln_roaebit.rsquared_adj, 4))

print("\nCoefficient clé :")
print("rate_change_x_vulnerable_2022 =", round(model_vuln_roaebit.params["rate_change_x_vulnerable_2022"], 6))
print("p-value =", round(model_vuln_roaebit.pvalues["rate_change_x_vulnerable_2022"], 6))

                                   coef   std_err    t_stat   p_value
policy_rate_change            -0.002170  0.003027 -0.716977  0.473388
rate_change_x_vulnerable_2022  0.005811  0.004059  1.431780  0.152207
size_ln_assets                 0.015143  0.050089  0.302318  0.762410

N observations : 576
R² : 0.8736
Adj. R² : 0.8067

Coefficient clé :
rate_change_x_vulnerable_2022 = 0.005811
p-value = 0.152207

In [10]:
import pandas as pd
import statsmodels.formula.api as smf

file_path = "/content/final_regression_dataset_v2.xlsx"   # adapte si besoin
df = pd.read_excel(file_path, sheet_name="regression_base")

# Base 2022 pour définir la vulnérabilité initiale
base_2022 = df[df["fiscal_year"] == 2022].copy()

# Seuils
lev_cut = base_2022["book_leverage"].quantile(0.67)
ic_cut = base_2022["interest_coverage"].quantile(0.33)

# Dummy de vulnérabilité
base_2022["vulnerable_2022"] = (
    (base_2022["book_leverage"] >= lev_cut) &
    (base_2022["interest_coverage"] <= ic_cut)
).astype(int)

# Merge dans la base panel
vuln_map = base_2022[["firm_id", "vulnerable_2022"]].copy()
df = df.merge(vuln_map, on="firm_id", how="left")

# Interaction avec la variation des taux
df["rate_change_x_vulnerable_2022"] = df["policy_rate_change"] * df["vulnerable_2022"]

print(df[["firm_id", "fiscal_year", "policy_rate_change", "vulnerable_2022", "rate_change_x_vulnerable_2022"]].head())
print(df["vulnerable_2022"].value_counts(dropna=False))

  firm_id  fiscal_year  policy_rate_change  vulnerable_2022  \
0    F001         2022                 NaN              0.0
1    F001         2023                1.23              0.0
2    F001         2024               -0.85              0.0
3    F001         2025               -0.76              0.0
4    F002         2022                 NaN              0.0

   rate_change_x_vulnerable_2022
0                            NaN
1                            0.0
2                           -0.0
3                           -0.0
4                            NaN
vulnerable_2022
0.0    639
1.0    136
NaN      6
Name: count, dtype: int64

In [11]:
reg_cols = [
    "firm_id",
    "fiscal_year",
    "interest_coverage",
    "policy_rate_change",
    "vulnerable_2022",
    "rate_change_x_vulnerable_2022",
    "size_ln_assets"
]

reg_last = df[reg_cols].dropna().copy()

print("Observations:", len(reg_last))
print("Firmes:", reg_last["firm_id"].nunique())
print("Années:", sorted(reg_last["fiscal_year"].unique()))

Observations: 573
Firmes: 195
Années: [np.int64(2023), np.int64(2024), np.int64(2025)]

In [12]:
model_last = smf.ols(
    "interest_coverage ~ policy_rate_change + rate_change_x_vulnerable_2022 + size_ln_assets + C(firm_id) + C(fiscal_year)",
    data=reg_last
).fit(cov_type="cluster", cov_kwds={"groups": reg_last["firm_id"]})

print(model_last.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      interest_coverage   R-squared:                       0.703
Model:                            OLS   Adj. R-squared:                  0.545
Method:                 Least Squares   F-statistic:                     170.1
Date:                Sun, 05 Apr 2026   Prob (F-statistic):           6.39e-69
Time:                        23:04:42   Log-Likelihood:                -3097.4
No. Observations:                 573   AIC:                             6595.
Df Residuals:                     373   BIC:                             7465.
Df Model:                         199
Covariance Type:              cluster
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                     -2195.8847   1766.196     -1.243      0.214   -5657.565    1265.796
C(firm_id)[T.F002]                3.1865     14.896      0.214      0.831     -26.008      32.381
C(firm_id)[T.F003]              280.8862    114.203      2.460      0.014      57.053     504.720
C(firm_id)[T.F004]              -43.9682     37.097     -1.185      0.236    -116.678      28.741
C(firm_id)[T.F005]              246.2976     17.353     14.194      0.000     212.287     280.308
C(firm_id)[T.F006]               91.3447     18.785      4.863      0.000      54.526     128.164
C(firm_id)[T.F007]               76.4415     72.292      1.057      0.290     -65.249     218.132
C(firm_id)[T.F008]               65.4989     65.892      0.994      0.320     -63.648     194.645
C(firm_id)[T.F010]              234.7407    167.517      1.401      0.161     -93.587     563.069
C(firm_id)[T.F011]               94.3962     77.645      1.216      0.224     -57.786     246.578
C(firm_id)[T.F012]               65.3493     64.710      1.010      0.313     -61.480     192.178
C(firm_id)[T.F013]              278.1204    191.482      1.452      0.146     -97.177     653.417
C(firm_id)[T.F014]              203.0138    166.477      1.219      0.223    -123.276     529.303
C(firm_id)[T.F015]              135.2973    110.227      1.227      0.220     -80.744     351.338
C(firm_id)[T.F016]              194.3177    159.136      1.221      0.222    -117.583     506.219
C(firm_id)[T.F017]              156.3785    128.941      1.213      0.225     -96.342     409.099
C(firm_id)[T.F018]              214.2024    161.084      1.330      0.184    -101.516     529.921
C(firm_id)[T.F019]              128.4044    113.658      1.130      0.259     -94.360     351.169
C(firm_id)[T.F020]              263.7245    213.924      1.233      0.218    -155.558     683.007
C(firm_id)[T.F021]              260.7755    198.911      1.311      0.190    -129.084     650.635
C(firm_id)[T.F022]              484.7357    201.791      2.402      0.016      89.233     880.238
C(firm_id)[T.F023]              267.2816    218.558      1.223      0.221    -161.084     695.647
C(firm_id)[T.F024]               28.4807     41.951      0.679      0.497     -53.742     110.703
C(firm_id)[T.F025]               51.7869     59.274      0.874      0.382     -64.388     167.962
C(firm_id)[T.F026]               97.6838     92.323      1.058      0.290     -83.265     278.633
C(firm_id)[T.F027]              135.3911    109.540      1.236      0.216     -79.303     350.085
C(firm_id)[T.F028]               64.4237     48.114      1.339      0.181     -29.878     158.725
C(firm_id)[T.F029]               68.4464     67.897      1.008      0.313     -64.629     201.522
C(firm_id)[T.F030]               85.8271     75.852      1.132      0.258     -62.840     234.494
C(firm_id)[T.F031]               26.7890     36.814      0.728      0.467     -45.365      98.943
C(firm_id)[T.F032]               92.6119     86.418      1.072      0.284     -76.765     261.989
C(firm_id)[T.F033]              120.5618    102.314      1.178      0.239     -79.969     321.093
C(firm_id)[T.F034]              123.8605    101.067      1.226      0.220     -74.228     321.949
C(firm_id)[T.F035]              242.0222    201.314      1.202      0.229    -152.546     636.590
C(firm_id)[T.F036]              177.4800    149.835      1.185      0.236    -116.191     471.151
C(firm_id)[T.F037]              168.8892    143.066      1.180      0.238    -111.516     449.294
C(firm_id)[T.F038]              184.9415    157.568      1.174      0.241    -123.886     493.769
C(firm_id)[T.F039]              266.5047    215.330      1.238      0.216    -155.535     688.544
C(firm_id)[T.F040]                5.4714     16.998      0.322      0.748     -27.845      38.787
C(firm_id)[T.F041]               99.1777     92.830      1.068      0.285     -82.766     281.121
C(firm_id)[T.F042]              243.0527    153.749      1.581      0.114     -58.290     544.395
C(firm_id)[T.F043]               13.8499     26.677      0.519      0.604     -38.436      66.136
C(firm_id)[T.F044]              139.0638    122.899      1.132      0.258    -101.814     379.942
C(firm_id)[T.F045]               57.9503     58.449      0.991      0.321     -56.607     172.508
C(firm_id)[T.F046]              157.3556    130.409      1.207      0.228     -98.242     412.953
C(firm_id)[T.F047]               35.6474     41.926      0.850      0.395     -46.526     117.821
C(firm_id)[T.F048]               10.7627     22.609      0.476      0.634     -33.551      55.076
C(firm_id)[T.F049]               30.2008     38.003      0.795      0.427     -44.284     104.685
C(firm_id)[T.F050]              -22.0439      6.398     -3.446      0.001     -34.583      -9.505
C(firm_id)[T.F051]              154.8827    134.180      1.154      0.248    -108.105     417.870
C(firm_id)[T.F052]              205.7964    174.634      1.178      0.239    -136.480     548.073
C(firm_id)[T.F053]              228.5297    190.584      1.199      0.230    -145.008     602.067
C(firm_id)[T.F054]              266.6259    223.064      1.195      0.232    -170.571     703.823
C(firm_id)[T.F055]              197.5172    166.083      1.189      0.234    -128.000     523.035
C(firm_id)[T.F056]              464.6596    152.127      3.054      0.002     166.496     762.824
C(firm_id)[T.F057]              162.1685    138.928      1.167      0.243    -110.126     434.463
C(firm_id)[T.F058]              113.6006     98.472      1.154      0.249     -79.401     306.602
C(firm_id)[T.F059]              262.9900    169.322      1.553      0.120     -68.874     594.854
C(firm_id)[T.F060]              308.0137    248.059      1.242      0.214    -178.174     794.201
C(firm_id)[T.F062]              148.6316    126.210      1.178      0.239     -98.736     395.999
C(firm_id)[T.F063]               94.4703     74.601      1.266      0.205     -51.745     240.685
C(firm_id)[T.F064]               96.7837     88.113      1.098      0.272     -75.914     269.481
C(firm_id)[T.F065]              102.2954     87.951      1.163      0.245     -70.086     274.676
C(firm_id)[T.F066]              133.4294    115.859      1.152      0.249     -93.650     360.509
C(firm_id)[T.F067]              147.5983    129.055      1.144      0.253    -105.344     400.541
C(firm_id)[T.F068]              256.5540    208.427      1.231      0.218    -151.956     665.064
C(firm_id)[T.F069]              121.3527     93.946      1.292      0.196     -62.779     305.484
C(firm_id)[T.F070]               87.4224     83.600      1.046      0.296     -76.431     251.276
C(firm_id)[T.F071]              127.2318    111.528      1.141      0.254     -91.358     345.822
C(firm_id)[T.F072]              145.4704    126.248      1.152      0.249    -101.971     392.912
C(firm_id)[T.F073]               50.1329     54.442      0.921      0.357     -56.571     156.837
C(firm_id)[T.F074]              145.9648    126.344      1.155      0.248    -101.665     393.595
C(firm_id)[T.F075]               51.7869     59.274      0.874      0.382     -64.388     167.962
C(firm_id)[T.F076]              127.3645    110.143      1.156      0.248     -88.511     343.240
C(firm_id)[T.F077]              108.9235     96.661      1.127      0.260     -80.528     298.375
C(firm_id)[T.F078]              128.6660    113.054      1.138      0.255     -92.916     350.248
C(firm_id)[T.F079]              166.7835    143.866      1.159      0.246    -115.188     448.755
C(firm_id)[T.F080]              202.0593    150.269      1.345      0.179     -92.463     496.582
C(firm_id)[T.F081]              200.5883    168.768      1.189      0.235    -130.191     531.367
C(firm_id)[T.F082]              244.6951    194.211      1.260      0.208    -135.951     625.341
C(firm_id)[T.F083]              257.3717    215.305      1.195      0.232    -164.617     679.361
C(firm_id)[T.F084]              221.2309    185.430      1.193      0.233    -142.206     584.667
C(firm_id)[T.F085]              240.7706    203.760      1.182      0.237    -158.591     640.132
C(firm_id)[T.F086]              133.0500    101.290      1.314      0.189     -65.474     331.574
C(firm_id)[T.F087]              183.7120    153.987      1.193      0.233    -118.096     485.520
C(firm_id)[T.F088]              156.5642    127.259      1.230      0.219     -92.860     405.988
C(firm_id)[T.F089]               27.3895     10.576      2.590      0.010       6.661      48.118
C(firm_id)[T.F090]               44.8848     20.117      2.231      0.026       5.456      84.314
C(firm_id)[T.F091]             -387.3579    361.045     -1.073      0.283   -1094.993     320.277
C(firm_id)[T.F092]             -356.5195    298.627     -1.194      0.233    -941.818     228.779
C(firm_id)[T.F093]             -157.0971    149.987     -1.047      0.295    -451.066     136.872
C(firm_id)[T.F094]              -57.3350    137.351     -0.417      0.676    -326.538     211.868
C(firm_id)[T.F095]              149.5839    174.320      0.858      0.391    -192.077     491.244
C(firm_id)[T.F096]             -296.5388    233.995     -1.267      0.205    -755.161     162.084
C(firm_id)[T.F097]              157.1316    125.178      1.255      0.209     -88.213     402.477
C(firm_id)[T.F098]             -364.7852    287.329     -1.270      0.204    -927.939     198.369
C(firm_id)[T.F099]             -141.7076    136.032     -1.042      0.298    -408.325     124.910
C(firm_id)[T.F100]              344.3341    141.065      2.441      0.015      67.851     620.817
C(firm_id)[T.F101]              493.2743    114.865      4.294      0.000     268.143     718.406
C(firm_id)[T.F102]             -110.1656    102.572     -1.074      0.283    -311.204      90.873
C(firm_id)[T.F103]             -118.9948    108.420     -1.098      0.272    -331.495      93.505
C(firm_id)[T.F104]             -165.4779    140.658     -1.176      0.239    -441.162     110.206
C(firm_id)[T.F105]               30.4765     74.840      0.407      0.684    -116.208     177.161
C(firm_id)[T.F106]             -250.4352    204.960     -1.222      0.222    -652.149     151.279
C(firm_id)[T.F107]             -355.3529    287.409     -1.236      0.216    -918.664     207.958
C(firm_id)[T.F108]             -217.7936    168.972     -1.289      0.197    -548.973     113.386
C(firm_id)[T.F109]             -235.7530    241.490     -0.976      0.329    -709.064     237.558
C(firm_id)[T.F110]             -309.5961    241.718     -1.281      0.200    -783.356     164.163
C(firm_id)[T.F111]              -10.2342      8.479     -1.207      0.227     -26.853       6.384
C(firm_id)[T.F112]               98.6694     84.549      1.167      0.243     -67.044     264.382
C(firm_id)[T.F113]              130.8277    107.581      1.216      0.224     -80.027     341.683
C(firm_id)[T.F114]              267.5529    213.970      1.250      0.211    -151.820     686.925
C(firm_id)[T.F115]               13.8245     21.287      0.649      0.516     -27.898      55.547
C(firm_id)[T.F116]              149.9964    122.775      1.222      0.222     -90.637     390.630
C(firm_id)[T.F117]              167.8114    139.503      1.203      0.229    -105.609     441.232
C(firm_id)[T.F118]               86.5410     79.009      1.095      0.273     -68.315     241.397
C(firm_id)[T.F119]              218.6289    177.008      1.235      0.217    -128.301     565.559
C(firm_id)[T.F120]               97.5321     81.733      1.193      0.233     -62.661     257.726
C(firm_id)[T.F121]               78.2081     70.616      1.108      0.268     -60.196     216.612
C(firm_id)[T.F122]              139.1629    119.957      1.160      0.246     -95.949     374.275
C(firm_id)[T.F123]               70.1586     65.422      1.072      0.284     -58.066     198.383
C(firm_id)[T.F124]              214.2045    177.367      1.208      0.227    -133.428     561.837
C(firm_id)[T.F125]              226.4318    183.057      1.237      0.216    -132.353     585.216
C(firm_id)[T.F126]              176.4452    157.279      1.122      0.262    -131.816     484.706
C(firm_id)[T.F127]              135.4096    125.240      1.081      0.280    -110.057     380.876
C(firm_id)[T.F128]               95.9344     97.999      0.979      0.328     -96.139     288.008
C(firm_id)[T.F129]              104.8677    105.330      0.996      0.319    -101.575     311.311
C(firm_id)[T.F130]              232.1962    199.432      1.164      0.244    -158.684     623.077
C(firm_id)[T.F131]              108.2544     98.264      1.102      0.271     -84.339     300.848
C(firm_id)[T.F132]              100.3491     94.221      1.065      0.287     -84.321     285.019
C(firm_id)[T.F133]              251.7537    220.489      1.142      0.254    -180.396     683.904
C(firm_id)[T.F134]              254.0832    221.757      1.146      0.252    -180.552     688.719
C(firm_id)[T.F135]              155.0754    135.143      1.147      0.251    -109.800     419.951
C(firm_id)[T.F136]              277.8483    164.685      1.687      0.092     -44.929     600.626
C(firm_id)[T.F138]              270.1436    236.277      1.143      0.253    -192.951     733.238
C(firm_id)[T.F140]              125.3557    122.619      1.022      0.307    -114.973     365.684
C(firm_id)[T.F141]               81.9226     63.777      1.285      0.199     -43.077     206.923
C(firm_id)[T.F142]              301.5856    187.208      1.611      0.107     -65.335     668.507
C(firm_id)[T.F143]              171.2791    126.179      1.357      0.175     -76.027     418.586
C(firm_id)[T.F144]               82.3109     72.252      1.139      0.255     -59.301     223.922
C(firm_id)[T.F145]               24.6146     19.870      1.239      0.215     -14.330      63.559
C(firm_id)[T.F146]               84.3843     71.654      1.178      0.239     -56.056     224.824
C(firm_id)[T.F147]              148.1147    119.640      1.238      0.216     -86.375     382.605
C(firm_id)[T.F148]              211.3675    133.438      1.584      0.113     -50.167     472.901
C(firm_id)[T.F149]              220.9238    176.736      1.250      0.211    -125.472     567.320
C(firm_id)[T.F150]               81.3457     72.571      1.121      0.262     -60.891     223.583
C(firm_id)[T.F151]              180.4566    150.312      1.201      0.230    -114.149     475.062
C(firm_id)[T.F152]              184.7008    152.611      1.210      0.226    -114.411     483.812
C(firm_id)[T.F153]              146.7040    126.519      1.160      0.246    -101.268     394.676
C(firm_id)[T.F154]              141.8728    119.373      1.188      0.235     -92.094     375.839
C(firm_id)[T.F155]               80.1891     74.188      1.081      0.280     -65.218     225.596
C(firm_id)[T.F156]              137.7811    111.113      1.240      0.215     -79.996     355.558
C(firm_id)[T.F157]               67.1501     60.314      1.113      0.266     -51.062     185.362
C(firm_id)[T.F158]               35.7625     25.256      1.416      0.157     -13.739      85.264
C(firm_id)[T.F159]               37.7133     25.325      1.489      0.136     -11.924      87.350
C(firm_id)[T.F160]              -54.6209     34.786     -1.570      0.116    -122.799      13.557
C(firm_id)[T.F161]              119.0241    104.835      1.135      0.256     -86.448     324.496
C(firm_id)[T.F162]               86.7038     81.870      1.059      0.290     -73.758     247.166
C(firm_id)[T.F163]              215.3358    170.131      1.266      0.206    -118.116     548.787
C(firm_id)[T.F164]                7.2373     17.988      0.402      0.687     -28.019      42.494
C(firm_id)[T.F165]              137.4152    113.431      1.211      0.226     -84.906     359.736
C(firm_id)[T.F166]              238.6744    196.612      1.214      0.225    -146.677     624.026
C(firm_id)[T.F167]              305.6140    224.882      1.359      0.174    -135.147     746.375
C(firm_id)[T.F168]              272.1779    218.339      1.247      0.213    -155.759     700.115
C(firm_id)[T.F169]              170.4734    139.176      1.225      0.221    -102.306     443.253
C(firm_id)[T.F170]              169.6475    134.159      1.265      0.206     -93.299     432.594
C(firm_id)[T.F171]               85.2209     71.168      1.197      0.231     -54.266     224.707
C(firm_id)[T.F172]              114.9052     90.594      1.268      0.205     -62.656     292.467
C(firm_id)[T.F173]              110.3611     86.165      1.281      0.200     -58.520     279.242
C(firm_id)[T.F174]              226.6504    146.456      1.548      0.122     -60.399     513.699
C(firm_id)[T.F175]              250.9266    200.983      1.248      0.212    -142.993     644.847
C(firm_id)[T.F176]              267.9816    213.138      1.257      0.209    -149.761     685.724
C(firm_id)[T.F177]              293.1212    231.398      1.267      0.205    -160.411     746.654
C(firm_id)[T.F178]              172.1328    140.682      1.224      0.221    -103.598     447.864
C(firm_id)[T.F179]              207.2195    167.693      1.236      0.217    -121.454     535.893
C(firm_id)[T.F180]              368.9994    278.510      1.325      0.185    -176.870     914.869
C(firm_id)[T.F181]              232.0775    139.678      1.662      0.097     -41.686     505.840
C(firm_id)[T.F182]              148.5669    115.552      1.286      0.199     -77.910     375.044
C(firm_id)[T.F183]              387.4047    234.800      1.650      0.099     -72.795     847.604
C(firm_id)[T.F184]              158.8149    135.024      1.176      0.240    -105.828     423.457
C(firm_id)[T.F185]              845.8502    288.941      2.927      0.003     279.537    1412.163
C(firm_id)[T.F186]              151.6260    128.947      1.176      0.240    -101.105     404.357
C(firm_id)[T.F187]              311.0275    245.472      1.267      0.205    -170.089     792.144
C(firm_id)[T.F188]              203.4951    171.856      1.184      0.236    -133.336     540.326
C(firm_id)[T.F189]              363.7046    293.696      1.238      0.216    -211.929     939.339
C(firm_id)[T.F190]              275.1406    213.909      1.286      0.198    -144.112     694.394
C(firm_id)[T.F191]              102.5949     85.783      1.196      0.232     -65.537     270.727
C(firm_id)[T.F192]              187.2473    152.890      1.225      0.221    -112.412     486.907
C(firm_id)[T.F193]              197.1511    160.425      1.229      0.219    -117.276     511.579
C(firm_id)[T.F194]              231.5051    174.690      1.325      0.185    -110.882     573.892
C(firm_id)[T.F195]              152.5258    121.366      1.257      0.209     -85.347     390.398
C(firm_id)[T.F196]              256.1323    196.886      1.301      0.193    -129.758     642.022
C(firm_id)[T.F197]              169.4403    141.286      1.199      0.230    -107.475     446.355

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 199, but rank is 5
  warnings.warn('covariance of constraints does not have full '

In [13]:
main_vars = [
    "policy_rate_change",
    "rate_change_x_vulnerable_2022",
    "size_ln_assets"
]

results_last = pd.DataFrame({
    "coef": model_last.params[main_vars],
    "std_err": model_last.bse[main_vars],
    "t_stat": model_last.tvalues[main_vars],
    "p_value": model_last.pvalues[main_vars]
})

print(results_last)

print("\nN observations :", int(model_last.nobs))
print("R² :", round(model_last.rsquared, 4))
print("Adj. R² :", round(model_last.rsquared_adj, 4))

print("\nCoefficient clé :")
print("rate_change_x_vulnerable_2022 =", round(model_last.params["rate_change_x_vulnerable_2022"], 6))
print("p-value =", round(model_last.pvalues["rate_change_x_vulnerable_2022"], 6))

                                    coef    std_err    t_stat   p_value
policy_rate_change            -22.389591  10.830194 -2.067331  0.038703
rate_change_x_vulnerable_2022  -1.019303   3.859655 -0.264092  0.791709
size_ln_assets                 84.716384  66.513023  1.273681  0.202776

N observations : 573
R² : 0.7033
Adj. R² : 0.545

Coefficient clé :
rate_change_x_vulnerable_2022 = -1.019303
p-value = 0.791709